export const DETAILREQUEST_START = 'DETAILREQUEST_START';
export const DETAILREQUEST_SUCCESS = 'DETAILREQUEST_SUCCESS';
export const DETAILREQUEST_FAIL = 'DETAILREQUEST_FAIL';

// LIKESCHANGE
export const EVENTLISTEN_START = 'EVENTLISTEN_START';
export const EVENTLISTEN_SUCCESS = 'EVENTLISTEN_SUCCESS';
export const EVENTLISTEN_FAIL = 'EVENTLISTEN_FAIL';

export const LIKEADD_START = 'LIKEADD_START';
export const LIKEADD_SUCCESS = 'LIKEADD_SUCCESS';
export const LIKEADD_FAIL = 'LIKEADD_FAIL';

export const LIKEINC_START = 'LIKEINC_START';
export const LIKEINC_SUCCESS = 'LIKEINC_SUCCESS';
export const LIKEINC_FAIL = 'LIKEINC_FAIL';

export const COMMENTADD_START = 'COMMENTADD_START';
export const COMMENTADD_SUCCESS = 'COMMENTADD_SUCCESS';
export const COMMENTADD_FAIL = 'COMMENTADD_FAIL';

export const BORROW_START = 'BORROW_START';
export const BORROW_SUCCESS = 'BORROW_SUCCESS';
export const BORROW_FAIL = 'BORROW_FAIL';

// LIKESCOLLATION
export const COMMENTREQUEST_START = 'COMMENTREQUEST_START';
export const COMMENTREQUEST_SUCCESS = 'COMMENTREQUEST_SUCCESS';
export const COMMENTREQUEST_FAIL = 'COMMENTREQUEST_FAIL';

export const COMMENTINC_START = 'COMMENTINC_START';
export const COMMENTINC_SUCCESS = 'COMMENTINC_SUCCESS';
export const COMMENTINC_FAIL = 'COMMENTINC_FAIL';

export const SETSHOW_SNACK = 'SETSHOW_SNACK';
export const SETHIDE_SNACK = 'SETHIDE_SNACK';

export const CLEAR_STATE = 'CLEAR_STATE';
