export const POST_REQUEST_START = 'POST_REQUEST_START';
export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS';
export const POST_REQUEST_FAIL = 'POST_REQUEST_FAIL';
export const CLEAR_STATE = 'CLEAR_STATE';
