export const BOOKREVIEW_START = 'BOOKREVIEW_START';
export const BOOKREVIEW_SUCCESS = 'BOOKREVIEW_SUCCESS';
export const BOOKREVIEW_FAIL = 'BOOKREVIEW_FAIL';
export const CLEAR_STATE = 'CLEAR_STATE';
