export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';
// LIKESCHANGE
export const EVENTLISTEN_START = 'EVENTLISTEN_START';
export const EVENTLISTEN_SUCCESS = 'EVENTLISTEN_SUCCESS';
export const EVENTLISTEN_FAIL = 'EVENTLISTEN_FAIL';
// LIKESCOLLATION
export const COLLATION_START = 'COLLATION_START';
export const COLLATION_SUCCESS = 'COLLATION_SUCCESS';
export const COLLATION_FAIL = 'COLLATION_FAIL';

export const CLEAR_STATE = 'CLEAR_STATE';
