export const MYPAGE_REQUEST_START = 'MYPAGE_REQUEST_START';
export const MYPAGE_REQUEST_SUCCESS = 'MYPAGE_REQUEST_SUCCESS';
export const MYPAGE_REQUEST_FAIL = 'MYPAGE_REQUEST_FAIL';
export const CLEAR_STATE = 'CLEAR_STATE';
