export const MYPAGE_REQUEST_START = 'MYPAGE_REQUEST_START';
export const MYPAGE_REQUEST_SUCCESS = 'MYPAGE_REQUEST_SUCCESS';
export const MYPAGE_REQUEST_FAIL = 'MYPAGE_REQUEST_FAIL';
export const RETURN_START = 'RETURN_START';
export const RETURN_SUCCESS = 'RETURN_SUCCESS';
export const RETURN_FAIL = 'RETURN_FAIL';

export const USERCOMMENTS_START = 'USERCOMMENTS_START';
export const USERCOMMENTS_SUCCESS = 'USERCOMMENTS_SUCCESS';
export const USERCOMMENTS_FAIL = 'USERCOMMENTS_FAIL';

export const USERLIKES_START = 'USERLIKES_START';
export const USERLIKES_SUCCESS = 'USERLIKES_SUCCESS';
export const USERLIKES_FAIL = 'USERLIKES_FAIL';

export const CLEAR_STATE = 'CLEAR_STATE';
